[package]
name = "nautilus-state-encoder"
version.workspace = true
edition.workspace = true
description = "Shared memory state encoder for Sextant"
license.workspace = true

[[bin]]
name = "cross_process_writer"
path = "tests/bin/cross_process_writer.rs"

[dependencies]
nautilus-core = { workspace = true }
nautilus-model = { workspace = true }
nautilus-common = { workspace = true }

memmap2 = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3"

[features]
default = []
